/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AddressBook;

import java.io.IOException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 * The main program window, List of addresses in the address 
 * book and the fields of the chosen address.
 * @author Alex Wikstrom
 */
public class main_FindAddress extends javax.swing.JFrame {



    Book addBook;  // 'Address book' connections to the database and all the addresses
    
    
     /**
     * Creates new form main_FindAddress
     * @throws java.sql.SQLException - Adds to and reads database
     * @throws java.lang.ClassNotFoundException - Connection parameters
     * @throws java.io.IOException - Connection parameters
     */
    
    public main_FindAddress() throws SQLException, IOException, ClassNotFoundException {
        initComponents();
        SimpleDataSource.init("database.properties");
        

        
        
        addBook = new Book();  // instantiate the address book
        
        String[] names = new String[addBook.GetLengthBook()];  // create a list of names from the address book

        for(int i = 0; i<addBook.GetLengthBook(); i++)  //  fill the list
        {
             names[i] = addBook.LastFirst(i);
        }
        Arrays.sort(names);

        
        jComboBox1.setModel(new DefaultComboBoxModel(names));  // replace combobox list with list of names
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 375));
        setSize(new java.awt.Dimension(300, 375));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("Address Line 2:");

        jLabel5.setText("City:");

        jLabel6.setText("State:");

        jLabel7.setText("Zip Code:");

        jLabel8.setText("Phone No:");

        jLabel9.setText("Email Address:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("FName");
        jLabel2.getAccessibleContext().setAccessibleName("LastName");
        jLabel3.getAccessibleContext().setAccessibleName("Address1");
        jLabel4.getAccessibleContext().setAccessibleName("Address2");
        jLabel5.getAccessibleContext().setAccessibleName("City");
        jLabel6.getAccessibleContext().setAccessibleName("State");
        jLabel6.getAccessibleContext().setAccessibleDescription("");
        jLabel7.getAccessibleContext().setAccessibleName("Zip");
        jLabel8.getAccessibleContext().setAccessibleName("Phone");
        jLabel9.getAccessibleContext().setAccessibleName("Email");
        jComboBox1.getAccessibleContext().setAccessibleName("cmbLastFirst");
        jButton1.getAccessibleContext().setAccessibleName("btnAdd");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String chosenName = (String)jComboBox1.getSelectedItem();
        String[] chosenInfo = new String[9];
        chosenInfo = addBook.GetChosenInfo(chosenName);
        
            jLabel1.setText("First Name: " + chosenInfo[0]);
            jLabel2.setText("Last Name: " + chosenInfo[1]);
            jLabel3.setText("Email Address: " + chosenInfo[2]);
            jLabel4.setText("Address: " + chosenInfo[3]);
            jLabel5.setText("Address Line 2: " + chosenInfo[4]);
            jLabel6.setText("City: " + chosenInfo[5]);
            jLabel7.setText("State: " + chosenInfo[6]);
            jLabel8.setText("Zip Code: " + chosenInfo[7]);
            jLabel9.setText("Phone No: " + chosenInfo[8]);

        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
     /**
     * Add Address, creates frame and disposes this one
     */
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new AddAddress(addBook).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
     * Deletes selected address and and calls refreshbox
     */
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        String chosenName = (String)jComboBox1.getSelectedItem();

        
        try {
            addBook.DeleteAddress(chosenName);
        } catch (SQLException ex) {
            Logger.getLogger(main_FindAddress.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            RefreshBox();
        } catch (SQLException ex) {
            Logger.getLogger(main_FindAddress.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

     /**
     * Empties labels and refreshes combobox 
     */
    
    private void RefreshBox() throws SQLException
    {
            jLabel1.setText("First Name: ");
            jLabel2.setText("Last Name: ");
            jLabel3.setText("Email Address: ");
            jLabel4.setText("Address: ");
            jLabel5.setText("Address Line 2: ");
            jLabel6.setText("City: ");
            jLabel7.setText("State: ");
            jLabel8.setText("Zip Code: ");
            jLabel9.setText("Phone No: ");
            
            
            
        addBook = new Book();
        
        String[] names = new String[addBook.GetLengthBook()];

        for(int i = 0; i<addBook.GetLengthBook(); i++)
        {
             names[i] = addBook.LastFirst(i);
        }
        
        Arrays.sort(names);
        jComboBox1.setModel(new DefaultComboBoxModel(names));
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_FindAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_FindAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_FindAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_FindAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main_FindAddress().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(main_FindAddress.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(main_FindAddress.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(main_FindAddress.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
